### ISSUE TITLE
backlogのサブドメインに「-」が入っていると、API_HOSTの正規表現でエラーになる

### ISSUE THREAD

**Issue by stmon19** [bicstone/backlog-notify#4]
# 概要
xxx-xxx.backlog.com
など、サブドメインに「-（ハイフン）」が入るとapiHostRegexでfalse判定されてしまいbacklog連携できない

# 要望
下記のようにハイフンが入ったサブドメインでも連携できると助かります。
`/^[a-z-\d]+\.backlog(\.com|\.jp|tool\.com)$/`
雑ですみません。

日本語で失礼しました…

**Comment by bicstone** [comment]
反映いたしました！
ありがとうございます！

**Comment by stmon19** [comment]
しっかり動きました！
助かりました！！

作っていただきありがとうございます！

**Comment by bicstone** [comment]
こちらこそプルリクエストまでして頂きありがとうございます。
