### ISSUE TITLE
違うIDのチケットにコミットが割り当てられる

### ISSUE THREAD

**Issue by stmon19** [bicstone/backlog-notify#6]
## 概要
EXAMPLE-123に紐付けたはずが、EXAMPLE-1にコミットが紐付いてしまいます。

## コミットメッセージ
EXAMPLE-123 xxx #fix

## 紐付けられるチケット
EXAMPLE-1

## チケットのメッセージ
23 xxx #fix

正規表現がおかしいみたいです。

**Comment by bicstone** [comment]
ご報告ありがとうございます。
確認いたします。

**Comment by bicstone** [comment]
反映いたしました。
修正頂きありがとうございます。
